baseURL = "http://arthurmasson.xyz"
title = "AM"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""

[pagination]
  pagerSize = 16

preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

# Missing translations will default to this content language
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[params.info]
description = "Arthur Masson works"
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["assets/css/custom.css"]
customJS = ["assets/js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Arthur Masson"
startYear = "2017"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideEntryMeta = ["page"] # boolean / array of sections
recentPostsLength = 4
hideSocialMenu = false
showReadingTime = true
noTermCloudShuffle = false

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
codepen = "ArthurMasson"
email = "arthur.yves.robin@gmail.com"
facebook = "ArthurMasson"
github = "arthursw"
instagram = "ArthurMasson"
linkedin = "arthurmasson"
twitter = "ArthurMasson"
telegram = "ArthurMasson"

[params.social.config]
platforms = ["github","email"]

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[permalinks]
page = "/:slug/"

[languages]
[languages.en]
title = "AM"
languageCode = 'en-US'
languageName = "English"
weight = 1
[[languages.en.menu.main]]
name = "AM"
weight = -220
identifier = "arthurmasson"
url = "/"
[[languages.en.menu.tags]]
name = "Applications"
identifier = "application"
url = "/tags/application/"
[[languages.en.menu.tags]]
name = "Reflections"
identifier = "reflection"
url = "/tags/reflection/"
[[languages.en.menu.tags]]
name = "Experiments"
identifier = "experiment"
url = "/tags/experiment/"
[[languages.en.menu.tags]]
name = "Websites"
identifier = "websites"
url = "/tags/website/"
[[languages.en.menu.tags]]
name = "Art"
identifier = "art"
url = "/tags/artwork/"
[[languages.en.menu.co]]
name = "La Sophiste"
identifier = "lasophiste"
url = "/tags/lasophiste/"
[[languages.en.menu.co]]
name = "IDLV"
identifier = "idlv"
url = "/tags/idlv/"
[[languages.en.menu.workamount]]
name = "1 to 18 hours"
identifier = "from1to18hours"
url = "/tags/from1to18hours/"
weight = 1
[[languages.en.menu.workamount]]
name = "1 to 18 days"
identifier = "from1to18days"
url = "/tags/from1to18days/"
weight = 2
[[languages.en.menu.workamount]]
name = "1 to 18 months"
identifier = "from1to18months"
url = "/tags/from1to18months/"
weight = 3

[languages.fr]
title = "AM"
languageCode = 'fr-FR'
languageName = "Français"
weight = 2
angledQuotes = true
# [languages.fr.settings]
# date & time format: https://golang.org/pkg/time/
# dateFormat = "02 January 2006"
# listDateFormat = "02 January 2006"
[[languages.fr.menu.main]]
name = "AM"
weight = -220
identifier = "arthurmasson"
url = "/fr/"
[[languages.fr.menu.tags]]
name = "Applications"
identifier = "application"
url = "/fr/tags/application/"
[[languages.fr.menu.tags]]
name = "Réflexions"
identifier = "reflection"
url = "/fr/tags/reflection/"
[[languages.fr.menu.tags]]
name = "Expériences"
identifier = "experiment"
url = "/fr/tags/experiment/"
[[languages.fr.menu.tags]]
name = "Sites web"
identifier = "website"
url = "/fr/tags/website/"
[[languages.fr.menu.tags]]
name = "Art"
identifier = "artwork"
url = "/fr/tags/artwork/"
[[languages.fr.menu.co]]
name = "La Sophiste"
identifier = "lasophiste"
url = "/fr/tags/lasophiste/"
[[languages.fr.menu.co]]
name = "IDLV"
identifier = "idlv"
url = "/fr/tags/idlv/"
[[languages.fr.menu.workamount]]
name = "1 à 18 heures"
identifier = "from1to18hours"
url = "/fr/tags/from1to18hours/"
weight = 1
[[languages.fr.menu.workamount]]
name = "1 à 18 jours"
identifier = "from1to18days"
url = "/fr/tags/from1to18days/"
weight = 2
[[languages.fr.menu.workamount]]
name = "1 à 18 mois"
identifier = "from1to18months"
url = "/fr/tags/from1to18months/"
weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  mainSections = ["post"]